In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
## sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good']

In [9]:
## Define the vocabulary size
voc_size=10000

In [11]:
## One hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6020, 6900, 3829, 3646],
 [6020, 6900, 3829, 3993],
 [6020, 5583, 3829, 2893],
 [8873, 5442, 2600, 7211, 8307],
 [8873, 5442, 2600, 7211, 8775],
 [4582, 6020, 7701, 3829, 2845],
 [7089, 4164, 9000, 7211]]

In [12]:
## Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6020 6900 3829 3646]
 [   0    0    0    0 6020 6900 3829 3993]
 [   0    0    0    0 6020 5583 3829 2893]
 [   0    0    0 8873 5442 2600 7211 8307]
 [   0    0    0 8873 5442 2600 7211 8775]
 [   0    0    0 4582 6020 7701 3829 2845]
 [   0    0    0    0 7089 4164 9000 7211]]


In [15]:
## Feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 75ms/step


2026-02-18 22:46:47.885620: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[-0.00132084,  0.00734342,  0.03543938,  0.01693242,
         -0.0470674 ,  0.04213842,  0.00751795,  0.01305186,
         -0.0378322 ,  0.03577243],
        [-0.00132084,  0.00734342,  0.03543938,  0.01693242,
         -0.0470674 ,  0.04213842,  0.00751795,  0.01305186,
         -0.0378322 ,  0.03577243],
        [-0.00132084,  0.00734342,  0.03543938,  0.01693242,
         -0.0470674 ,  0.04213842,  0.00751795,  0.01305186,
         -0.0378322 ,  0.03577243],
        [-0.00132084,  0.00734342,  0.03543938,  0.01693242,
         -0.0470674 ,  0.04213842,  0.00751795,  0.01305186,
         -0.0378322 ,  0.03577243],
        [ 0.03262994, -0.0005262 , -0.01621132, -0.02707801,
         -0.04860343, -0.04444757,  0.04262361, -0.02633931,
          0.00480451, -0.01939021],
        [ 0.03441494, -0.01150943, -0.02677033, -0.04961887,
          0.04608062, -0.01192271, -0.01400892, -0.0464674 ,
          0.0154967 ,  0.04584361],
        [ 0.00017396,  0.01422106, -0.02326685,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6020, 6900, 3829, 3646], dtype=int32)

In [20]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 29ms/step


array([[-0.00132084,  0.00734342,  0.03543938,  0.01693242, -0.0470674 ,
         0.04213842,  0.00751795,  0.01305186, -0.0378322 ,  0.03577243],
       [-0.00132084,  0.00734342,  0.03543938,  0.01693242, -0.0470674 ,
         0.04213842,  0.00751795,  0.01305186, -0.0378322 ,  0.03577243],
       [-0.00132084,  0.00734342,  0.03543938,  0.01693242, -0.0470674 ,
         0.04213842,  0.00751795,  0.01305186, -0.0378322 ,  0.03577243],
       [-0.00132084,  0.00734342,  0.03543938,  0.01693242, -0.0470674 ,
         0.04213842,  0.00751795,  0.01305186, -0.0378322 ,  0.03577243],
       [ 0.03262994, -0.0005262 , -0.01621132, -0.02707801, -0.04860343,
        -0.04444757,  0.04262361, -0.02633931,  0.00480451, -0.01939021],
       [ 0.03441494, -0.01150943, -0.02677033, -0.04961887,  0.04608062,
        -0.01192271, -0.01400892, -0.0464674 ,  0.0154967 ,  0.04584361],
       [ 0.00017396,  0.01422106, -0.02326685,  0.04668907, -0.03409163,
         0.03891157,  0.03244323, -0.04018775